/*
 *  MyVersion.c
 *  Molby
 *
 *  Created by Toshi Nagata on 09/10/16.
 *  Copyright 2008-2014 Toshi Nagata. All rights reserved.
 *
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation version 2 of the License.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 */

const char *gVersionString = "v1.0b2";
const char *gCopyrightString = "Copyright (c) 2008-2014 Toshi Nagata";
/*  The following are now defined in build/buildInfo.c, generated by record_build_date.sh  */
/*int gRevisionNumber = 0;
char *gLastBuildString = (char *)0; */
